In [2]:
%pip install transformers torch

Note: you may need to restart the kernel to use updated packages.


In [4]:
import torch
from transformers import AutoTokenizer, AutoModel


In [8]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")



In [31]:
sentence1 = "she took a rose from the garden"
sentence2 = "Sun Rose in the Morning"

In [34]:
inputs1 = tokenizer(sentence1, return_tensors="pt",padding=True)["input_ids"]
print(inputs1)
inputs2 = tokenizer(sentence2, return_tensors="pt")["input_ids"]
print(inputs2)

tensor([[ 101, 2016, 2165, 1037, 3123, 2013, 1996, 3871,  102]])
tensor([[ 101, 3103, 3123, 1999, 1996, 2851,  102]])


In [41]:
with torch.no_grad():
    outputs1 = model(inputs1).last_hidden_state
    outputs2 = model(inputs2).last_hidden_state

print(outputs1.shape)
print(outputs2)

torch.Size([1, 9, 768])
tensor([[[ 0.1335, -0.0445, -0.0803,  ..., -0.3845,  0.4394,  0.2239],
         [ 0.4131,  0.2301,  0.6103,  ..., -0.2093,  0.4158, -0.2105],
         [-0.3513,  0.4579,  0.6087,  ..., -0.5381, -0.3672, -0.3372],
         ...,
         [ 0.1335,  0.0230,  0.5292,  ..., -0.8617,  0.5151, -0.7192],
         [-0.1403, -0.3112, -0.1248,  ...,  0.3822,  0.1952, -1.2322],
         [ 0.6872, -0.0447, -0.1156,  ...,  0.3279, -0.1201, -0.4776]]])
